const quotes = [
    "Ak akçe, kara gün içindir.",
    "Ak koyunun, kara kuzusuda olur.",
    "Akıllı hırsız, şaşkın ev sahibini bastırır.",
    "Akıllı düşman, akılsız dosttan hayırlıdır.",
    "Alma mazlumun ahını, çıkar aheste aheste.",
    "Anlayana sivrisinek saz,anlamayana davul zurna az.",
    "Arpa iken buğday biçilmez.",
    "Ateş olmayan yerden,duman çıkmaz.",
    "At ölür meydan kalır, yiğit ölür şan kalır.",
    "Aza kanaat etmeyen, çoğu hiç bulamaz.",
    "Bal bal demekle, ağız tatlanmaz.",
    "Ben diyorum kısırım, sen diyorsun kaç çocuğun var.",
    "Bıçağı kestiren kendi suyu, insanı sevdiren kendi huyu.",
    "Birlikten kuvvet doğar.",
    "Bir elin nesi var ,iki elin sesi var.",
    "Bin dost az,bir düşman çok.",
    "Bugünün işini ,yarına bırakma.",
    "Cefayı çekmeyen, safanın kadrini bilmez.",
    "Çobansız koyunu,kurt kapar.",
    "Dağ dağa kavuşmaz,insan insana kavuşur.",
    "Davulun sesi ,uzaktan hoş gelir.",
    "Derdini söylemeyen, derman bulamaz.",
    "Dervişin fikri ne ise zikride odur.",
    "Deveyi yardan uçuran, bir tutam ottur.",
    "Deveden büyük,fil var.",
    "Dost ile ye iç, alışveriş yapma.",
    "Dost başa, düşman ayağa bakar.",
    "Eğri otur,düz (doğru) konuş.",
    "El yarası onulur,dil yarası onulmaz.",
    "Er (Yiğit-Çalışkan ) olan ,ekmeğini taştan çıkarır.",
    "Erkek Arslan,dişisinden kuvvet alır.",
    "Esirgenen göze, çöp batar.",
    "Eski düşman dost olmaz, olsa da dürüst olmaz.",
    "Eşeğe altın semer vursalar, eşek yine eşektir.",
    "Eşeği düğüne çağırmışlar; ya odun eksik, ya su demiş.",
    "Eşek bile düştüğü yere, bir daha düşmez.",
    "Fazla mal,göz çıkarmaz.",
    "Garip kuşun yuvasını,Allah yapar.",
    "Geçmişini bilmeyen, geleceğini göremez.",
    "Gönül kimi severse, güzel odur.",
    "Gören gözün , hakkı vardır.",
    "Görünen köy, kılavuz istemez.",
    "Gülme komşuna, gelir başına.",
    "Gülü seven, dikenine katlanır.",
    "Güneş girmeyen eve,doktor girer.",
    "Güvenme varlığa, düşersin darlığa.",
    "Her deliğe elini sokma,ya yılan çıkar ya çıyan.",
    "Her horoz, kendi çiftliğinde öter.",
    "Her yiğidin, bir yoğurt yiğişi vardır.",
    "İğneyi kendine ,çuvaldızı başkasına batır.",
    "İnsan yedisinde ne ise yetmişinde de odur.",
    "İsteyenin bir yüzü, vermeyenin iki yüzü.",
    "İşten artmaz, dişten artar.",
    "İyi dost , kara günde belli olur.",
    "İyi olacak hastanın, hekim ayağına gelir.",
    "Kâr,zararın kardeşidir.",
    "Kanı kanla yumazlar, kanı su ile yurlar.",
    "Kara haber, tez ( çabuk ) duyulur.",
    "Kızı keyfine bırakırsan. ya davulcuya varır yada zurnacıya varır.",
    "Korkulu rüya görmektense,uyanık yatmak hayırlıdır.",
    "Korkunun ecele faydası yok.",
    "Köprüyü geçinceye kadar, ayı&#8217;ya dayı diyecen.",
    "Kurunun yanında, yaşda yanar.",
    "Küçük suda , büyük balık olmaz.",
    "Mart kapıdan baktırır, kazma kürek yaktırır.",
    "Mazlumun ahı , indirir şahı.( yerde kalmaz)",
    "Misafir umduğunu değil, bulduğunu yer.",
    "Ne doğrarsan aşına, o çokar karşına.",
    "Ne oldum dememeli,ne olacağım demeli.",
    "Oynamasını bilmeyen gelin, yerim dar dermiş.",
    "Öğretmenin vurduğu, yerde gül biter.",
    "Önce iğneyi kendine batır, sonra çuvaldızı ele.",
    "Paran varsa cümle alem kulun,paran yoksa tımarhane yolun.",
    "Rüşvet kapıdan girince, imam bacadan çıkar.",
    "Rüzgara tüküren, kendi yüzüne tükürür.",
    "Sana taşla vurana , sen aşla vur.",
    "Sen ağa ben ağa, inekleri kim sağa.",
    "Seyrek git dostuna, kalksın ayak üstüne.",
    "Sinek küçüktür ama mide bulandırır.",
    "Sütten ağzı yanan , yoğurdu üfleyerek yer.",
    "Sade pirinç zerde olmaz, bal gerektir kazana; baba malı tez tükenir evlat gerek kazana.",
    "Sade pirinç zerde olmaz,bal da gerek kazana;ata malı tez tükenir,evlat gerek kazana.",
    "Sarmısağı gelin etmişler, kırk gün kokusu çıkmamış.",
    "Şahin gözünü ette açmış; karga gözünü bokta açmış.",
    "Şer işi uzat hayra dönsün, hayır işi uzatma şerre dönmesin.",
    "Şubatın sonundan, martın onundan kork.",
    "Tabancanın dolusu bir kişiyi korkutur, boşu kırk kişiyi.",
    "Tarlada izi olmayanın harmanında yüzü olmaz.",
    "Taş çömleğe çarparsa vay çömleğin haline, çömlek taşa çarparsa yine vay çömleğin.",
    "Tilkiye tavuk kebabı yer misin demişler; adamın güleceğini getiriyorsunuz demiş.",
    "Ucuna bak bezini al, anasına bak kızını al.",
    "Ucuzdur vardır illeti, pahalıdır vardır hikmeti.",
    "Üveye etme, özünde bulursun; geline etme, kızında bulursun.",
    "Üç kuruşluk eşeğin beş paralık sıpası olur.",
    "Üveye etme, özünde bulursun; geline etme, kızında bulursun.",
    "Vardı bağım malım, gelirdi kardeşlerim; tükendi yağım balım, gelmiyor kardeşlerim.",
    "Varsa hünerin, var her yerde yerin; yoksa hünerin, var her yerde yerin.",
    "Verip pişman olmaktan, vermeyip düşman olmak yeğdir.",
    "Varsa hünerin, var her yerde yerin; yoksa hünerin, var her yerde yerin.",
    "Yaman komşu, yaman avrat, yaman at; birinden göç, birin boşa, birin sat.",
    "Yaprağa yapış, atlas olsun; toprağa yapış, altın olsun.",
    "Yarım hekim candan eder, yarım hoca dinden eder.",
    "Zengin helvasını baldan pişirir, züğürt derman için pekmez bulamaz.",
    "Zengin giyerse sağlıcakla, fakir giyerse nerden buldu ki derler.",
    "Hacı hacı olmaz gitmekle Mekke&#8217;ye, dede dede olmaz gitmekle tekkeye.",
    "Halayıktan kadın olmaz, gül ağacından odun olmaz.",
    "Ihlamurdan odun olmaz, beslemeden kadın olmaz.",
    "Işığını akşamdan önce yakan, sabah çırasına yağ bulamaz.",
    "Kalendere kış geliyor demişler, titremeye hazırım diye cevap vermiş.",
    "Karakışta karlar, martta yağmaz, nisanda durmazsa değme çiftçinin keyfine.",
    "Lafla pilav pişerse deniz kadar yağı benden.",
    "Mal istersen bedeninden, evlat istersen belinden.",
    "Malını yemesini bilmeyen zengin her gün züğürttür.",
    "Nush ile uslanmayanı etmeli tekdir, tekdir ile uslanmayanın hakkı kötektir.",
    "Oğlan babasından öğrenir yazı yazmayı, kız anasından öğrenir sokak gezmeyi.",
    "Oynamasını bilmeyen kız; yerim dar demiş; yerini genişletmişler ; gerim.",
    "Öksüz hırsızlığa çıkarsa ay ilk akşamdan doğar.",
    "Öküz öküzün boynuzunda çamur görmezse korkmaz.",
    "Param seni vereyim de mi düşman olayım, vermeyeyim de mi düşman olayım?",
    "Parayı domuzun boynuna takmışlar da Domuz Ağa! diye çağırmışlar.",
    "Ramazan bereketli aydır, ama duvardan giden kılıca sor.",
    "Ramazanda yalan söyleyenin bayramda yüzü kara olsun.",
    "Sabahın kızıllığı akşamı kış eder; akşamın kızıllığı sabahı güz eder.",
    "Dağ dağa kavuşmaz, kişi kişiye kavuşur.",
    "Kimsenin yaptığı, yanına kalmaz.",
    "Sinek küçüktür, ama mide bulandırır.",
    "Allah kardeşi kardeş yaratmış, kesesini ayrı yaratmış.",
    "Âdemoğlu hîlebâzdır, kimse bilmez fendini! Her kime rağbet edersen, sakın andan kendini.",
    "Ağaca da çıksa pabucu yerde kalmaz Tarif edilen kişinin hem kurnaz, hem de tedbirli olduğunu ima eder.",
    "Allah isterse bir kulun işini, mermere geçirir dişini; istemezse işini, muhallebi yerken.",
    "Baba oğluna bir bağ bağışlamış, oğul babaya bir salkım üzüm vermemiş.",
    "Bana benden olur, her ne olursa, başım rahat bulur, dilim durursa.",
    "Başım acemi berbere teslim eden, cebinden pamuğunu eksik etmez.",
    "Canı kaymak isteyen, mandayı yanında taşır.",
    "Çiftçiye yağmur, yolcuya kurak; cümlenin muradını verecek Hak.",
    "Çağrıldığın yere git, ar eyleme; çağrılmadığın yere gidip yerini dar eyleme.",
    "Dağ başına harman yapma, savurursun yel için, sel önüne değirmen yapma, öğütürsün.",
    "Deh! denmiş dünyayı, Çüş! diye sen mi durduracaksın?.",
    "Deme dostuna, der dostuna. Bir gün olur tuz basarlar postuna.",
    "Ekincinin karnını yarmışlar; kırk bu yılcık, kırk bıldırcık çıkmış.",
    "Fincancı katırını ürküten sayısız dayak yer.",
    "Gece yağar gündüz açar, yıl düzgünlüğü; erkek söyler kadın susar, ev düzgünlüğü."
]

export default function get() {
    return quotes[Math.floor(Math.random() * quotes.length)];
}

//zemi.space